spring:
  application:
    name: zuul-service

server:  port: 5555    

eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
  instance:    prefer-ip-address: true
    
zuul:
  prefix: /api  
 
  routes:    organizations-service : /org-service/**
    licenses-service: /lic-service/**
 
logging:  level:   
    com.netflix: error
    org.springframework.web: error
    com.lamin: debug